const CartActionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_FROM_CART: "CLEAR_FROM_CART",
  MAKE_ORDER_START: "MAKE_ORDER_START",
  MAKE_ORDER_SUCCESS: "MAKE_ORDER_SUCCESS",
  MAKE_ORDER_FAILURE: "MAKE_ORDER_FAILURE"
};

export default CartActionTypes;
