const AuthActionTypes = {
  AUTHENTICATE_POC_START: "SIGN_UP_START",
  AUTHENTICATE_POC_SUCCESS: "SIGN_UP_SUCCESS",
  AUTHENTICATE_POC_FAILURE: "SIGN_UP_FAILURE",
  AUTHENTICATE_DISTRIBUTOR_START: "SIGN_UP_DISTRIBUTOR_START",
  AUTHENTICATE_DISTRIBUTOR_SUCCESS: "SIGN_UP_DISTRIBUTOR_SUCCESS",
  AUTHENTICATE_DISTRIBUTOR_FAILURE: "SIGN_UP_DISTRIBUTOR_FAILURE",
  AUTHENTICATE_BULK_BREAKER_START: "SIGN_UP_BULK_BREAKER_START",
  AUTHENTICATE_BULK_BREAKER_SUCCESS: "SIGN_UP_BULK_BREAKER_SUCCESS",
  AUTHENTICATE_BULK_BREAKER_FAILURE: "SIGN_UP_BULK_BREAKER_FAILURE",
};

export default AuthActionTypes;
