const AuthActionTypes = {
  SIGN_UP_POC_START: "SIGN_UP_START",
  SIGN_UP_POC_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_POC_FAILURE: "SIGN_UP_FAILURE",
  SIGN_IN_POC_START: "SIGN_IN_START",
  SIGN_IN_POC_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_POC_FAILURE: "SIGN_IN_FAILURE",
  SIGN_UP_DISTRIBUTOR_START: "SIGN_UP_DISTRIBUTOR_START",
  SIGN_UP_DISTRIBUTOR_SUCCESS: "SIGN_UP_DISTRIBUTOR_SUCCESS",
  SIGN_UP_DISTRIBUTOR_FAILURE: "SIGN_UP_DISTRIBUTOR_FAILURE",
  SIGN_IN_DISTRIBUTOR_START: "SIGN_IN_DISTRIBUTOR_START",
  SIGN_IN_DISTRIBUTOR_SUCCESS: "SIGN_IN_DISTRIBUTOR_SUCCESS",
  SIGN_IN_DISTRIBUTOR_FAILURE: "SIGN_IN_DISTRIBUTOR_FAILURE",
  SIGN_UP_BULK_BREAKER_START: "SIGN_UP_BULK_BREAKER_START",
  SIGN_UP_BULK_BREAKER_SUCCESS: "SIGN_UP_BULK_BREAKER_SUCCESS",
  SIGN_UP_BULK_BREAKER_FAILURE: "SIGN_UP_BULK_BREAKER_FAILURE",
  SIGN_IN_BULK_BREAKER_START: "SIGN_IN_BULK_BREAKER_START",
  SIGN_IN_BULK_BREAKER_SUCCESS: "SIGN_IN_BULK_BREAKER_SUCCESS",
  SIGN_IN_BULK_BREAKER_FAILURE: "SIGN_IN_BULK_BREAKER_FAILURE",
};

export default AuthActionTypes;
