const AuthActionTypes = {
  AUTHENTICATE_POC_START: "AUTHENTICATE_POC_START",
  AUTHENTICATE_POC_SUCCESS: "AUTHENTICATE_POC_SUCCESS",
  AUTHENTICATE_POC_FAILURE: "AUTHENTICATE_POC_FAILURE",
  AUTHENTICATE_DISTRIBUTOR_START: "AUTHENTICATE_DISTRIBUTOR_START",
  AUTHENTICATE_DISTRIBUTOR_SUCCESS: "AUTHENTICATE_DISTRIBUTOR_SUCCESS",
  AUTHENTICATE_DISTRIBUTOR_FAILURE: "AUTHENTICATE_DISTRIBUTOR_FAILURE",
  AUTHENTICATE_BULK_BREAKER_START: "AUTHENTICATE_BULK_BREAKER_START",
  AUTHENTICATE_BULK_BREAKER_SUCCESS: "AUTHENTICATE_BULK_BREAKER_SUCCESS",
  AUTHENTICATE_BULK_BREAKER_FAILURE: "AUTHENTICATE_BULK_BREAKER_FAILURE",
  SET_ELIGIBILITY: "SET_ELIGIBILITY"
};

export default AuthActionTypes;
