const OrderActionTypes = {
    FETCH_RECEIVED_ORDERS_START: "FETCH_RECEIVED_ORDERS_START",
    FETCH_RECEIVED_ORDERS_SUCCESS: "FETCH_RECEIVED_ORDERS_SUCCESS",
    FETCH_RECEIVED_ORDERS_FAILURE: "FETCH_RECEIVED_ORDERS_FAILURE",

    FETCH_SENT_ORDERS_START: "FETCH_SENT_ORDERS_START",
    FETCH_SENT_ORDERS_SUCCESS: "FETCH_SENT_ORDERS_SUCCESS",
    FETCH_SENT_ORDERS_FAILURE: "FETCH_SENT_ORDERS_FAILURE",

    UPDATE_ORDER_START: "UPDATE_ORDER_START",
    UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",
    UPDATE_ORDER_FAILURE: "UPDATE_ORDER_FAILURE",
};

export default OrderActionTypes;
