const MapActionTypes = {
  FETCH_MARKERS_START: "FETCH_MARKERS_START",
  FETCH_MARKERS_SUCCESS: "FETCH_MARKERS_SUCCESS",
  FETCH_MARKERS_FAILURE: "FETCH_MARKERS_FAILURE",
};

export default MapActionTypes;
