const UserActionTypes = {
  FETCH_POCS_START: "FETCH_POCS_START",
  FETCH_POCS_SUCCESS: "FETCH_POCS_SUCCESS",
  FETCH_POCS_FAILURE: "FETCH_POCS_FAILURE",
  FETCH_DISTRIBUTORS_START: "FETCH_DISTRIBUTORS_START",
  FETCH_DISTRIBUTORS_SUCCESS: "FETCH_DISTRIBUTORS_SUCCESS",
  FETCH_DISTRIBUTORS_FAILURE: "FETCH_DISTRIBUTORS_FAILURE",
  FETCH_BULK_BREAKERS_START: "FETCH_BULK_BREAKERS_START",
  FETCH_BULK_BREAKERS_SUCCESS: "FETCH_BULK_BREAKERS_SUCCESS",
  FETCH_BULK_BREAKERS_FAILURE: "FETCH_BULK_BREAKERS_FAILURE",
};

export default UserActionTypes;
