const UserActionTypes = {
  FETCH_POCS_START: "FETCH_POCS_START",
  FETCH_POCS_SUCCESS: "FETCH_POCS_SUCCESS",
  FETCH_POCS_FAILURE: "FETCH_POCS_FAILURE",
  FETCH_DISTRIBUTORS_START: "FETCH_DISTRIBUTORS_START",
  FETCH_DISTRIBUTORS_SUCCESS: "FETCH_DISTRIBUTORS_SUCCESS",
  FETCH_DISTRIBUTORS_FAILURE: "FETCH_DISTRIBUTORS_FAILURE",
  FETCH_BULK_BREAKERS_START: "FETCH_BULK_BREAKERS_START",
  FETCH_BULK_BREAKERS_SUCCESS: "FETCH_BULK_BREAKERS_SUCCESS",
  FETCH_BULK_BREAKERS_FAILURE: "FETCH_BULK_BREAKERS_FAILURE",
  UPDATE_POCS_START: "UPDATE_POCS_START",
  UPDATE_POCS_SUCCESS: "UPDATE_POCS_SUCCESS",
  UPDATE_POCS_FAILURE: "UPDATE_POCS_FAILURE",
  UPDATE_DISTRIBUTORS_START: "UPDATE_DISTRIBUTORS_START",
  UPDATE_DISTRIBUTORS_SUCCESS: "UPDATE_DISTRIBUTORS_SUCCESS",
  UPDATE_DISTRIBUTORS_FAILURE: "UPDATE_DISTRIBUTORS_FAILURE",
  UPDATE_BULK_BREAKERS_START: "UPDATE_BULK_BREAKERS_START",
  UPDATE_BULK_BREAKERS_SUCCESS: "UPDATE_BULK_BREAKERS_SUCCESS",
  UPDATE_BULK_BREAKERS_FAILURE: "UPDATE_BULK_BREAKERS_FAILURE",

  CHECK_DISTRIBUTOR_START: "CHECK_DISTRIBUTOR_START",
  CHECK_DISTRIBUTOR_SUCCESS: "CHECK_DISTRIBUTOR_SUCCESS",
  CHECK_DISTRIBUTOR_FAILURE: "CHECK_DISTRIBUTOR_FAILURE"
};

export default UserActionTypes;
