const PasswordAction = {
    PASSWORD_DISTRIBUTOR_START: "PASSWORD_DISTRIBUTOR_STARTT",
    PASSWORD_DISTRIBUTOR_SUCCESS: "PASSWORD_DISTRIBUTOR_SUCCESS",
    PASSWORD_DISTRIBUTOR_FAILURE: "PASSWORD_DISTRIBUTOR_FAILURE",
    PASSWORD_BULKBREAKER_START: "PASSWORD_BULKBREAKER_START",
    PASSWORD_BULKBREAKER_SUCCESS: "PASSWORD_BULKBREAKER_SUCCESS",
    PASSWORD_BULKBREAKER_FAILURE: "PASSWORD_BULKBREAKER_FAILURE",
    PASSWORD_POC_START: "PASSWORD_POC_START",
    PASSWORD_POC_SUCCESS: "PASSWORDE_POC_SUCCESS",
    PASSWORD_POC_FAILURE: "AUTHENTICATE_DISTRIBUTOR_PASSWORD",
    SET_ELIGIBILITY: "SET_ELIGIBILITY"
  };
  
  export default PasswordAction;
  